---
# L027: This role has no meta/main.yml

- name: Echo broken role task message
  command: echo "I am a broken role task"

- name: Do something risky in the role
  ansible.builtin.shell: rm -rf /tmp/old_data/*
  become: true # noqa: R108
